# Generated by Django 4.2.6 on 2023-10-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='foods/')),
                ('type', models.CharField(choices=[('l', 'Lunch'), ('d', 'Drinks'), ('d', 'Dinner')], default='Lunch', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
