# Generated by Django 4.2.6 on 2023-10-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamifood', '0002_food_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
