# Generated by Django 4.2.6 on 2023-10-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamifood', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('work_fields', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='staf/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
