# Generated by Django 4.2.6 on 2023-10-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamifood', '0004_staf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staf',
            new_name='Staff',
        ),
    ]
