# Generated by Django 4.2.6 on 2023-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamifood', '0005_rename_staf_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to='media/staf/'),
        ),
    ]
